Style/FrozenStringLiteralComment:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'db/schema.rb'
    - 'config/initializers/devise.rb'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 162

Metrics/PerceivedComplexity:
  Max: 15

Metrics/CyclomaticComplexity:
  Max: 15

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Style/RedundantBegin:
  Exclude:
    - 'bin/yarn'

Style/StderrPuts:
  Exclude:
    - 'bin/yarn'

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Naming/MemoizedInstanceVariableName:
  Exclude:
    - 'app/services/message_service.rb'

Style/StringLiterals:
  Exclude:
    - 'bin/yarn'
    - 'config/puma.rb'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Metrics/BlockLength:
  Exclude:
    - 'db/schema.rb'
    - 'spec/requests/news_items_spec.rb'
    - 'config/environments/production.rb'
    - 'config/environments/development.rb'

Style/ExpandPathArguments:
  Exclude:
    - 'bin/rails'
    - 'bin/rake'
    - 'spec/rails_helper.rb'

Style/WordArray:
  Exclude:
    - 'db/schema.rb'
